---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role journals
#

JOURNALS_GIT_IDENTITY: !!null

#
# vars are namespace with the module name.
#
journals_service_name: "journals"
journals_gunicorn_port: 8606

journals_environment:
  JOURNALS_CFG: "{{ COMMON_CFG_DIR }}/{{ journals_service_name }}.yml"

journals_user: "{{ journals_service_name }}"
journals_home: "{{ COMMON_APP_DIR }}/{{ journals_service_name }}"
journals_code_dir: "{{ journals_home }}/{{ journals_service_name }}"

#
# OS packages
#

journals_debian_pkgs:
  - libxml2-dev
  - libxslt-dev
  - libjpeg-dev


JOURNALS_NGINX_PORT: "1{{ journals_gunicorn_port }}"
JOURNALS_SSL_NGINX_PORT: "4{{ journals_gunicorn_port }}"

JOURNALS_DEFAULT_DB_NAME: 'journals'
JOURNALS_MYSQL: 'localhost'
# MySQL usernames are limited to 16 characters
JOURNALS_MYSQL_USER: 'journ001'
JOURNALS_MYSQL_PASSWORD: 'password'

# Using SSL? See https://www.elastic.co/guide/en/shield/current/ssl-tls.html.
# Using AWS? Use the AWS-provided host (e.g. https://search-test-abc123.us-east-1.es.amazonaws.com/).
# Assuming the port corresponds that of the protocol (e.g. http=80, https=443), there is no need to specify a port.
JOURNALS_ELASTICSEARCH_URL: 'http://127.0.0.1:9200/'
JOURNALS_ELASTICSEARCH_INDEX_NAME: 'journals'

JOURNALS_MEMCACHE: [ 'memcache' ]

JOURNALS_VERSION: "master"
JOURNALS_DJANGO_SETTINGS_MODULE: "journals.settings.production"
JOURNALS_URL_ROOT: 'http://journals:{{ JOURNALS_NGINX_PORT }}'
JOURNALS_LOGOUT_URL: '{{ JOURNALS_URL_ROOT }}/logout/'

JOURNALS_SECRET_KEY: 'Your secret key here'

JOURNALS_LANGUAGE_CODE: 'en'

## Configuration for django-parler package. For more information visit
## https://django-parler.readthedocs.io/en/latest/configuration.html#parler-languages
JOURNALS_PARLER_DEFAULT_LANGUAGE_CODE: '{{JOURNALS_LANGUAGE_CODE}}'
JOURNALS_PARLER_LANGUAGES :
  1:
    - code: 'en'
  default:
    fallbacks:
      - '{{JOURNALS_PARLER_DEFAULT_LANGUAGE_CODE}}'
    hide_untranslated: 'False'

JOURNALS_DEFAULT_PARTNER_ID: 1
JOURNALS_SESSION_EXPIRE_AT_BROWSER_CLOSE: false

# Used to automatically configure OAuth2 Client
JOURNALS_SOCIAL_AUTH_EDX_OIDC_KEY : 'journals-key'
JOURNALS_SOCIAL_AUTH_EDX_OIDC_SECRET : 'journals-secret'
JOURNALS_SOCIAL_AUTH_REDIRECT_IS_HTTPS: false

JOURNALS_PLATFORM_NAME: 'Your Platform Name Here'

JOURNALS_DATA_DIR: '{{ COMMON_DATA_DIR }}/{{ journals_service_name }}'
JOURNALS_MEDIA_ROOT: '{{ JOURNALS_DATA_DIR }}/media'
JOURNALS_MEDIA_URL: '/media/'

JOURNALS_MEDIA_STORAGE_BACKEND:
  DEFAULT_FILE_STORAGE: 'django.core.files.storage.FileSystemStorage'
  MEDIA_ROOT: '{{ JOURNALS_MEDIA_ROOT }}'
  MEDIA_URL: '{{ JOURNALS_MEDIA_URL }}'

JOURNALS_STATICFILES_STORAGE: 'django.contrib.staticfiles.storage.StaticFilesStorage'

# You can set different email backends with django:
# https://docs.djangoproject.com/en/1.9/topics/email/#email-backends
JOURNALS_EMAIL_BACKEND: 'django_ses.SESBackend'

# For email backend django-ses, the following settings are required
JOURNALS_AWS_SES_REGION_NAME: 'us-east-1'
JOURNALS_AWS_SES_REGION_ENDPOINT: 'email.us-east-1.amazonaws.com'

# For default email backend SMTP, following settings are required
JOURNALS_EMAIL_HOST: 'localhost'
JOURNALS_EMAIL_PORT: 25
JOURNALS_EMAIL_USE_TLS: False
JOURNALS_EMAIL_HOST_USER: ''
JOURNALS_EMAIL_HOST_PASSWORD: ''

JOURNALS_PUBLISHER_FROM_EMAIL: !!null

JOURNALS_OPENEXCHANGERATES_API_KEY: ''

JOURNALS_GUNICORN_EXTRA: ''

JOURNALS_EXTRA_APPS: []

JOURNALS_REPOS:
  - PROTOCOL: "{{ COMMON_GIT_PROTOCOL }}"
    DOMAIN: "{{ COMMON_GIT_MIRROR }}"
    PATH: "{{ COMMON_GIT_PATH }}"
    REPO: 'journals.git'
    VERSION: "{{ JOURNALS_VERSION }}"
    DESTINATION: "{{ journals_code_dir }}"
    SSH_KEY: "{{ JOURNALS_GIT_IDENTITY }}"

journals_service_config_overrides:
  ELASTICSEARCH_URL: '{{ JOURNALS_ELASTICSEARCH_URL }}'
  ELASTICSEARCH_INDEX_NAME: '{{ JOURNALS_ELASTICSEARCH_INDEX_NAME }}'

  PLATFORM_NAME: '{{ JOURNALS_PLATFORM_NAME }}'

  DEFAULT_PARTNER_ID: '{{ JOURNALS_DEFAULT_PARTNER_ID }}'

  EMAIL_BACKEND: '{{ JOURNALS_EMAIL_BACKEND }}'

  # Settings for django-ses email backend
  AWS_SES_REGION_NAME: '{{ JOURNALS_AWS_SES_REGION_NAME }}'
  AWS_SES_REGION_ENDPOINT: '{{ JOURNALS_AWS_SES_REGION_ENDPOINT }}'

  # Settings for default django SMTP email backend
  EMAIL_HOST: '{{ JOURNALS_EMAIL_HOST }}'
  EMAIL_PORT: '{{ JOURNALS_EMAIL_PORT }}'
  EMAIL_USE_TLS: '{{ JOURNALS_EMAIL_USE_TLS }}'
  EMAIL_HOST_USER: '{{ JOURNALS_EMAIL_HOST_USER }}'
  EMAIL_HOST_PASSWORD: '{{ JOURNALS_EMAIL_HOST_PASSWORD }}'

  PUBLISHER_FROM_EMAIL: '{{ JOURNALS_PUBLISHER_FROM_EMAIL }}'

  OPENEXCHANGERATES_API_KEY: '{{ JOURNALS_OPENEXCHANGERATES_API_KEY }}'

  LANGUAGE_CODE: '{{JOURNALS_LANGUAGE_CODE}}'
  PARLER_DEFAULT_LANGUAGE_CODE: '{{JOURNALS_PARLER_DEFAULT_LANGUAGE_CODE}}'
  PARLER_LANGUAGES : '{{JOURNALS_PARLER_LANGUAGES}}'
  CSRF_COOKIE_SECURE: "{{ JOURNALS_CSRF_COOKIE_SECURE }}"

# See edx_django_service_automated_users for an example of what this should be
JOURNALS_AUTOMATED_USERS: {}

JOURNALS_CSRF_COOKIE_SECURE: false

journals_create_demo_data: false

journals_post_migrate_commands:
  - command: './manage.py create_site --sitename "Test Site" --hostname "testsite.localhost" --port "18606"'
    when: false
